/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import automatas.SandPile;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.color.ColorSpace;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author JIMENO
 */
public class CanvasDibujoPile extends javax.swing.JPanel {
    public int[][] puntos;
   
    /**
     * Creates new form CanvasDibujo
     */
    public CanvasDibujoPile() {
        initComponents();
    
    }
    
    
    public void modificarPuntos(){
        
        SandPile sand = new SandPile();
        int j = 0;
        int timerDelay = 1;
        
        new Timer(timerDelay, new ActionListener(){
          public void actionPerformed(ActionEvent e) {
            int[] point = sand.limitExist(sand.grid);
            while(point != null){
                /*for(int i = 0; i<sand.grid.length; i++){for(int j = 0; j<sand.grid.length; j++){System.out.print(sand.grid[i][j]);}System.out.println("");}
                System.out.println("");*/
                puntos = sand.grid;
                repaint();
                sand.grid = sand.pile(sand.grid, point);
                point = sand.limitExist(sand.grid);
            }
            sand.grid = sand.sumPile(sand.grid);
              repaint();
          }
        }).start();
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        //Graphics2D g2 = (Graphics2D)g;
        int incremento = 3;
        int incrementox = 0;
        int incrementoy = 0;
        
        try{
            if(!puntos.equals(null)){
                int tami = puntos.length;
                for(int i = 0; i<tami;i++){
                    int tamj = puntos[i].length;
                    incrementox = 0;
                    
                    for(int j = 0; j<tamj;j++){
                        switch(puntos[i][j]){
                            case 0:
                                g.setColor(Color.black);
                                break;
                            case 1:
                                g.setColor(Color.green);
                                break;
                            case 2:
                                g.setColor(Color.yellow);
                                break;
                            case 3:
                                g.setColor(Color.orange);
                                break;
                            case 4:
                                g.setColor(Color.red);
                                break;
                        }
                        g.fillOval(incrementox, incrementoy, incremento, incremento);
                        
                        incrementox += incremento;
                    }
                    incrementoy += incremento;
                }
            }
        }catch(Exception e){System.out.println("Error al pintar: " + e);}
      }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
