/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author JIMENO
 */
public class CanvasDibujo extends javax.swing.JPanel {
    public int[][] puntos;
    /**
     * Creates new form CanvasDibujo
     */
    public CanvasDibujo() {
        initComponents();
    }
    public void modificarPuntos(int[][] puntos){
        this.puntos = puntos;
        repaint();
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        //Graphics2D g2 = (Graphics2D)g;
        int incremento = 1;
        int incrementox = 0;
        int incrementoy = 0;
        try{
            if(!puntos.equals(null)){
                int tami = puntos.length;
                for(int i = 0; i<tami;i++){
                    int tamj = puntos[i].length;
                    incrementox = 0;
                    for(int j = 0; j<tamj;j++){
                        if(puntos[i][j] == 1){
                            g.drawOval(incrementox, incrementoy, 1, 1);
                        }
                        incrementox += incremento;
                    }
                    incrementoy += incremento;
                }
            }
        }catch(Exception e){}
      }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
